# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170524_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='partners',
            field=models.ManyToManyField(default=None, related_name='tasks', to='department.Employee'),
        ),
    ]
