# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170410_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
