# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170524_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='department.Employee'),
        ),
    ]
